Solentive.Interview.WebUI/Controllers/BaseController.cs
using Solentive.Interview.Logging.Interfaces;
using System.Web.Mvc;

namespace Solentive.Interview.WebUI.Controllers
{
    public class BaseController : Controller
    {
        public ILoggingService _loggingService;

        public BaseController(ILoggingService loggingService)
        {
            _loggingService = loggingService;
        }

        protected override void OnException(ExceptionContext filterContext)
        {
            if (filterContext == null)
                base.OnException(filterContext);

            _loggingService.LogError(filterContext.Exception.ToString());
        }
    }
}

Solentive.Interview.WebUI/Controllers/ErrorController.cs
using System.Web.Mvc;

namespace Solentive.Interview.WebUI.Controllers
{
    public class ErrorController : Controller
    {
        public ViewResult Index()
        {
            return View("error");
        }

        public ViewResult NotFound()
        {
            Response.StatusCode = 404;
            return View("NotFound");
        }
    }
}

Solentive.Interview.WebUI/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Solentive.Interview.WebUI.Controllers
{
    public class HomeController : Controller
    {
        public HomeController()
        {}

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult About()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Contact()
        {
            return View();
        }
    }
}

Solentive.Interview.WebUI/Controllers/LevelController.cs
using Solentive.Interview.Logging.Interfaces;
using Solentive.Interview.Model;
using Solentive.Interview.Service.Interfaces;
using System.Linq;
using System.Web.Mvc;

namespace Solentive.Interview.WebUI.Controllers
{
    public class LevelController : BaseController
    {
        public ILevelService _levelService;

        public LevelController(ILevelService levelService, ILoggingService loggingService) : base(loggingService)
        {
            _levelService = levelService;
            _loggingService = loggingService;
        }

        [HttpGet]
        public ActionResult List()
        {
            // Get the source list and map to the view model type.
            var targetList = _levelService.GetLevels().ToList();
            return View(targetList);
        }

        [HttpGet]
        public ActionResult Add()
        {
            var model = new Level();
            return View(model);
        }

        [HttpPost]
        public ActionResult Add(Level level)
        {
            if (ModelState.IsValid)
            {
                var status = _levelService.AddLevel(level) ? "Saved Successfully!" : "Could not Save!";
                return Json(status);
            }
            return View(level);
        }
    }
}

Solentive.Interview.WebUI/Controllers/LocationController.cs
using Solentive.Interview.Logging.Interfaces;
using Solentive.Interview.Model;
using Solentive.Interview.Service.Interfaces;
using System.Web.Mvc;

namespace Solentive.Interview.WebUI.Controllers
{
    public class LocationController : BaseController
    {
        private readonly ILocationService _locationService;

        public LocationController(ILocationService locationService, ILoggingService loggingService) : base(loggingService)
        {
            _locationService = locationService;
            _loggingService = loggingService;
        }

        [HttpGet]
        public ActionResult List()
        {
            // Get the source list and map to the view model type.
            var list = _locationService.GetLocations();
            return View(list);
        }

        [HttpGet]
        public ActionResult Add()
        {
            var model = new Location();
            return View(model);
        }


        [HttpPost]
        public ActionResult Add(Location location)
        {
            if (ModelState.IsValid)
            {
                var status = _locationService.AddLocation(location) ? "Saved Successfully!" : "Could not Save!";
                return Json(status);
            }
            return View(location);
        }
    }
}

Solentive.Interview.WebUI/Controllers/SeminarController.cs
using Solentive.Interview.Common;
using Solentive.Interview.Logging.Interfaces;
using Solentive.Interview.Service.Interfaces;
using System;
using System.Web.Mvc;

namespace Solentive.Interview.WebUI.Controllers
{
    public class SeminarController : BaseController
    {      

        private readonly ISeminarService _seminarService;

        public SeminarController(ISeminarService seminarService, ILoggingService loggingService) : base(loggingService)
        {
            _seminarService = seminarService;
            _loggingService = loggingService;
        }

        [HttpGet]
        public ActionResult List()
        {
            // Set the week start and end
            ViewBag.WeekStart = DateCalculations.GetWeekStartDate(DateTime.Now).ToShortDateString();
            ViewBag.WeekEnd = DateCalculations.GetWeekEndDate(DateTime.Now).ToShortDateString();

            // Get the source list and map to the view model type.
            var list = _seminarService.GetSeminars();
            return View(list);
        }
    }
}

Solentive.Interview.WebUI/Controllers/TrackController.cs
using Solentive.Interview.Logging.Interfaces;
using Solentive.Interview.Model;
using Solentive.Interview.Service.Interfaces;
using System.Web.Mvc;

namespace Solentive.Interview.WebUI.Controllers
{
    public class TrackController : BaseController
    {
        private readonly ITrackService _trackService;

        public TrackController(ITrackService trackService, ILoggingService loggingService) : base(loggingService)
        {
            _trackService = trackService;
            _loggingService = loggingService;
        }

        [HttpGet]
        public ActionResult List()
        {
            // Get the source list and map to the view model type.
            var list = _trackService.GetTracks();
            return View("List",list);
        }

        [HttpGet]
        public ActionResult Add()
        {
            var model = new Track();
            return View(model);
        }

        [HttpPost]
        public ActionResult Add(Track track)
        {
            if (ModelState.IsValid)
            {
                var status = _trackService.AddTrack(track) ? "Saved Successfully!" : "Could not Save!";
                return Json(status);
            }
            return View(track);
        }
    }
}

Solentive.Interview.WebUI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<div class="well" data-ng-controller="welcome as vm">
    <h2>About</h2>
    <p>
        Seminar is an application that manages sessions, lectures and seminars.
    </p>
</div>

Solentive.Interview.WebUI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<div class="well" data-ng-controller="welcome as vm">
    <h2>Contact Us</h2>
    <section class="contact">
        <header>
            <h3>Phone</h3>
        </header>
        <p>
            <span class="label">Main:</span>
            <span>425.555.0100</span>
        </p>
        <p>
            <span class="label">After Hours:</span>
            <span>425.555.0199</span>
        </p>
    </section>

    <section class="contact">
        <header>
            <h3>Email</h3>
        </header>
        <p>
            <span class="label">Support:</span>
            <span><a href="mailto:Support@example.com">Support@example.com</a></span>
        </p>
        <p>
            <span class="label">Marketing:</span>
            <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
        </p>
        <p>
            <span class="label">General:</span>
            <span><a href="mailto:General@example.com">General@example.com</a></span>
        </p>
    </section>

    <section class="contact">
        <header>
            <h3>Address</h3>
        </header>
        <p>
            One Surry Hills Street<br />
            Surry Hills, NSW 2010
        </p>
    </section>
</div>

Solentive.Interview.WebUI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}
<div class="well">
    <h2>Welcome</h2>
    <p>
        Welcome to Seminar!
    </p>
    <p>
        Please use the menu on the left to browse our seminars.  You can also view the tracks we currently have with
        additional information about the locations of our lectures, sessions and seminars together with their level
        of complexity.
    </p>
</div>

Solentive.Interview.WebUI/Views/Level/Add.cshtml
@model Solentive.Interview.Model.Level

@{
    ViewBag.Title = "Add Level";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("", "", FormMethod.Post, new { @id = "addLevelForm" }))
{
    <div class="well container">
        <div class="row">
            <div class="col-md-12">
                <h2>Levels - Add</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                Name:
            </div>
            <div class="col-md-10">
                @Html.TextBox("Name", Model.Name)
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">&nbsp;</div>
            <div class="col-md-10">
                &nbsp;@Html.ValidationMessageFor(i => i.Name)
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                Scaling:
            </div>
            <div class="col-md-10">
                @Html.TextBox("Scaling", Model.Scaling)
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">&nbsp;</div>
            <div class="col-md-10">
                &nbsp;@Html.ValidationMessageFor(i => i.Scaling)
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">&nbsp;</div>
            <div class="col-md-10">
                <div id="divResultLevel"></div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <button id="btnSaveLevel" class="btn btn-primary">
                    <span class="glyphicon glyphicon-ok-circle"></span>&nbsp;Save
                </button>&nbsp;
                <a href="@Url.Action("List", "Level")" class="btn btn-primary">
                    <span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span>
                    Cancel
                </a>
            </div>
        </div>
    </div>
}

Solentive.Interview.WebUI/Views/Level/List.cshtml
@model List<Solentive.Interview.Model.Level>

@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts
{
    <script>
        $(document).ready(function () {
            $("#btnAddNewLevel").on("click", function () {
                window.location = '@Url.Action("Add", "Level")';
            });
        });
    </script>
}

<div class="well">
    <div class="row">
        <div class="col-md-12">
            <h2>Levels - List</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <button id="btnAddNewLevel" class="btn btn-primary">
                <span class="glyphicon glyphicon-plus"></span>&nbsp;Add
            </button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Scaling</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Name</td>
                            <td>@item.Scaling</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Solentive.Interview.WebUI/Views/Location/Add.cshtml
@model Solentive.Interview.Model.Location

@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("", "", FormMethod.Post, new { @id = "addLocationForm" }))
{
    <div class="well container">
        <div class="row">
            <div class="col-md-12">
                <h2>Locations - Add</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                Name:
            </div>
            <div class="col-md-10">
                @Html.TextBox("Name", Model.Name)
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">&nbsp;</div>
            <div class="col-md-10">
                &nbsp;@Html.ValidationMessageFor(i => i.Name)
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                Room Number
            </div>
            <div class="col-md-10">
                @Html.TextBox("RoomNumber", Model.RoomNumber)
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">&nbsp;</div>
            <div class="col-md-10">
                &nbsp;@Html.ValidationMessageFor(i => i.RoomNumber)
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                Building:
            </div>
            <div class="col-md-10">
                @Html.TextBox("Building", Model.Building)
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">&nbsp;</div>
            <div class="col-md-10">
                &nbsp;@Html.ValidationMessageFor(i => i.Building)
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">&nbsp;</div>
            <div class="col-md-10">
                <div id="divResult"></div>
            </div>
        </div>
        @if (ViewBag.HasSaved != null && ViewBag.HasSaved)
        {
            <div class="row">
                <div class="col-md-2">&nbsp;</div>
                <div class="col-md-10">
                    Saved Successfully
                </div>
            </div>
        }
        <div class="row">
            <div class="col-md-12">
                <button id="btnSaveLocation" class="btn btn-primary">
                    <span class="glyphicon glyphicon-ok-circle"></span>&nbsp;Save
                </button>&nbsp;
                <a href="@Url.Action("List", "Location")" class="btn btn-primary">
                    <span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span>
                    Cancel
                </a>
            </div>
        </div>
    </div>
}

Solentive.Interview.WebUI/Views/Location/List.cshtml
@model List<Solentive.Interview.Model.Location>

@{
    ViewBag.Title = "Locations";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts
{
    <script>
        $(document).ready(function () {
            $("#btnAddNewLocation").on("click", function () {
                window.location = '@Url.Action("Add", "Location")';
            });
        });
    </script>
}

<div class="well">
    <div class="row">
        <div class="col-md-12">
            <h2>Locations - List</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <button id="btnAddNewLocation" class="btn btn-primary">
                <span class="glyphicon glyphicon-plus"></span>&nbsp;Add
            </button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Room Number</th>
                        <th>Building</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Name</td>
                            <td>@item.RoomNumber</td>
                            <td>@item.Building</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Solentive.Interview.WebUI/Views/Seminar/List.cshtml
@model List<Solentive.Interview.Model.Seminar>

@{
    ViewBag.Title = "Seminars";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="well">
    <div class="row">
        <div class="col-md-12">
            <h2>Seminars - List</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 title">
            Current Week Start (Monday):
        </div>
        <div class="col-md-2">
            @ViewBag.WeekStart
        </div>
        <div class="col-md-4 title">
            Current Week End (Sunday):
        </div>
        <div class="col-md-2">
            @ViewBag.WeekEnd
        </div>

    </div>
    <div class="row">
        <div class="col-md-12 table-responsive">
            <table class="table seminar-table table-striped table-responsive">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Title</th>
                        <th>Date</th>
                        <th>Days To Go</th>
                        <th>Code</th>
                        <th>Description</th>
                        <th>Track</th>
                        <th>Location</th>
                        <th>Level</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Title</td>
                            <td>@item.Date.ToShortDateString()</td>
                            <td>@item.DaysToGo</td>
                            <td>@item.Code</td>
                            <td>@item.Description</td>
                            <td>@item.Track.Name</td>
                            <td>@item.Location.Name</td>
                            <td>@item.Level.Name</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Solentive.Interview.WebUI/Views/Shared/_Header.cshtml
<header>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#"></a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/Home">Home</a></li>
                    <li><a href="/Home/About">About</a></li>
                    <li><a href="/Home/Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </div>
</header>

Solentive.Interview.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET MVC Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    @Styles.Render("~/Content/bootstrap")
    @Styles.Render("~/Content/custom")
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
</head>
<body>
    <div id="main-content">
        @Html.Partial("_Header")

        <div class="container main-content">
            <div class="row-fluid">
                <div class="col-md-3">
                    @Html.Partial("_Navigation")
                </div>
                <div class="col-md-9">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/appscripts")
    @Scripts.Render("~/bundles/validation")
    @RenderSection("scripts", required: false)
</body>
</html>

Solentive.Interview.WebUI/Views/Shared/_Navigation.cshtml
<div class="well">
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-body">
                <a href="/Seminar/List" data-ng-class="vm.isCurrent(i)">
                    <span class="glyphicon glyphicon-book"></span>&nbsp;Seminars
                </a>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-body">
                <a href="/Track/List" data-ng-class="vm.isCurrent(i)">
                    <span class="glyphicon glyphicon-road"></span>&nbsp;Tracks
                </a>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-body">
                <a href="/Location/List" data-ng-class="vm.isCurrent(i)">
                    <span class="glyphicon glyphicon-tasks"></span>&nbsp;Locations
                </a>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-body">
                <a href="/Level/List" data-ng-class="vm.isCurrent(i)">
                    <span class="glyphicon glyphicon-th-list"></span>&nbsp;Levels
                </a>
            </div>
        </div>
    </div>
</div>

Solentive.Interview.WebUI/Views/Track/Add.cshtml
@model Solentive.Interview.Model.Track

@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("", "", FormMethod.Post, new { @id = "addTrackForm" }))
{
    var bl = BundleTable.Bundles;
    <div class="well container">
        <div class="row">
            <div class="col-md-12">
                <h2>Tracks - Add</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                Name:
            </div>
            <div class="col-md-10">
                @Html.TextBox("Name", Model.Name)
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">&nbsp;</div>
            <div class="col-md-10">
                &nbsp;@Html.ValidationMessageFor(i => i.Name)
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">&nbsp;</div>
            <div class="col-md-10">
                <div id="divResultTrack"></div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <button id="btnSaveTrack" class="btn btn-primary">
                    <span class="glyphicon glyphicon-ok-circle"></span>&nbsp;Save
                </button>&nbsp;
                <a href="@Url.Action("List", "Track")" class="btn btn-primary">
                    <span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span>
                    Cancel
                </a>
            </div>
        </div>
    </div>
}

Solentive.Interview.WebUI/Views/Track/List.cshtml
@model List<Solentive.Interview.Model.Track>
@{
    ViewBag.Title = "Tracks";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts
{
    <script>
        $(document).ready(function () {
            $("#btnAddNewTrack").on("click", function () {
                window.location = '@Url.Action("Add", "Track")'
            });
        });
    </script>
}

<div class="well">
    <div class="row">
        <div class=" col-md-12">
            <h2>Tracks - List</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <button id="btnAddNewTrack" class="btn btn-primary">
                <span class="glyphicon glyphicon-plus"></span>&nbsp;Add
            </button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Name</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>